### PR TITLE
Fixes various small things

### PR DESCRIPTION
**Pull request by LukeWood**
- Updates typescript compiler to use paths to handle package linking
(better for live reload)

- Updates the Application in GameManager to use the window's
devicePixelRatio to prevent gaps between sprites (this is a problem
when creating a map with 32x32 pixels)

### CODE REVIEW

**Comment by LukeWood** [comment]
amended commit to also:

- Adds AutoDensity so rendering works the same with the native
devicePixelRatio
- Fixes circle clamping - you could clip out of the left end of the map
and couldn't reach the far right.

**Comment by halftheopposite** [comment]
@LukeWood Thank you for your PR, I've been quite busy lately and sadly didn't get the chance to work on the project as I had expected, but I'll test and merge it this weekend if everything is good 👍. There is something I need to check on `yarn` workspaces first and packages linking.

**Comment by LukeWood** [comment]
sounds good!  Don't sweat it no rush.

I am not using your deployment stuff actually so I very well may have broken that without realizing.

Thanks again for publishing tosios - it really helped me kick start my game :).

**Comment by LukeWood** [comment]
p.s. - linked you in my credits :). https://tp-scramble.io/credits. t

**Comment by halftheopposite** [comment]
@LukeWood Thanks for quoting me in your credits! Concerning your changes, I have actually refactored the whole configuration for workspaces, TypeScript and eslint. So now the paths and reload work especially well! Thanks for your first insights which gave me motivation to do this refactor (along other things). It will be shipped in 0.12.0

**Pull request closed without merging**
